import { ProductType } from "./types";

export const initialProducts: ProductType[] = [
  {
    id: 1,
    name: "Product 1",
    type: 1,
    price: 100,
    availability: true,
    quantity: 10,
  },
  {
    id: 2,
    name: "Product 2",
    type: 2,
    price: 200,
    availability: true,
    quantity: 20,
  },
  {
    id: 3,
    name: "Product 3",
    type: 3,
    price: 300,
    availability: false,
    quantity: 30,
  },
  {
    id: 4,
    name: "Product 4",
    type: 4,
    price: 400,
    availability: true,
    quantity: 40,
  },
  {
    id: 5,
    name: "Product 5",
    type: 5,
    price: 500,
    availability: true,
    quantity: 50,
  },
  {
    id: 6,
    name: "Product 6",
    type: 6,
    price: 600,
    availability: false,
    quantity: 60,
  },
  {
    id: 7,
    name: "Product 7",
    type: 7,
    price: 700,
    availability: true,
    quantity: 70,
  },
  {
    id: 8,
    name: "Product 8",
    type: 8,
    price: 800,
    availability: true,
    quantity: 80,
  },
  {
    id: 9,
    name: "Product 9",
    type: 9,
    price: 900,
    availability: false,
    quantity: 90,
  },
  {
    id: 10,
    name: "Product 10",
    type: 10,
    price: 1000,
    availability: true,
    quantity: 100,
  },
  {
    id: 11,
    name: "Product 11",
    type: 11,
    price: 1100,
    availability: true,
    quantity: 110,
  },
  {
    id: 12,
    name: "Product 12",
    type: 12,
    price: 1200,
    availability: false,
    quantity: 120,
  },
  {
    id: 13,
    name: "Product 13",
    type: 13,
    price: 1300,
    availability: true,
    quantity: 130,
  },
  {
    id: 14,
    name: "Product 14",
    type: 14,
    price: 1400,
    availability: true,
    quantity: 140,
  },
  {
    id: 15,
    name: "Product 15",
    type: 15,
    price: 1500,
    availability: false,
    quantity: 150,
  },
  {
    id: 16,
    name: "Product 16",
    type: 16,
    price: 1600,
    availability: true,
    quantity: 160,
  },
  {
    id: 17,
    name: "Product 17",
    type: 17,
    price: 1700,
    availability: true,
    quantity: 170,
  },
  {
    id: 18,
    name: "Product 18",
    type: 18,
    price: 1800,
    availability: false,
    quantity: 180,
  },
  {
    id: 19,
    name: "Product 19",
    type: 19,
    price: 1900,
    availability: true,
    quantity: 190,
  },
  {
    id: 20,
    name: "Product 20",
    type: 20,
    price: 2000,
    availability: true,
    quantity: 200,
  },
  {
    id: 21,
    name: "Product 21",
    type: 20,
    price: 2000,
    availability: true,
    quantity: 200,
  },
];
